home.index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

home.about:
    path:     /about
    defaults: { _controller: AppBundle:Home:about }

map.index:
    path:     /map
    defaults: { _controller: AppBundle:Map:index }
