services:
    app_bundle.repository.tracks:
        class: AppBundle\Repository\Tracks
        calls:
            - [setConnection, ['@doctrine.dbal.default_connection']]
    app_bundle.repository.trackslevels:
            class: AppBundle\Repository\TracksLevels
            calls:
                - [setConnection, ['@doctrine.dbal.default_connection']]